#!/bin/bash
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/YouTube/YouTube.yaml -O /usr/share/caddy/clash_rules/YouTube.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Apple/Apple.yaml -O /usr/share/caddy/clash_rules/Apple.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Clubhouse/Clubhouse.yaml -O /usr/share/caddy/clash_rules/Clubhouse.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ClubhouseIP/ClubhouseIP.yaml -O /usr/share/caddy/clash_rules/ClubhouseIP.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/TikTok/TikTok.yaml -O /usr/share/caddy/clash_rules/TikTok.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/JOOX/JOOX.yaml -O /usr/share/caddy/clash_rules/JOOX.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Spotify/Spotify.yaml -O /usr/share/caddy/clash_rules/Spotify.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml -O /usr/share/caddy/clash_rules/Speedtest.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ChinaMedia/ChinaMedia.yaml -O /usr/share/caddy/clash_rules/ChinaMedia.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/China/China.yaml -O /usr/share/caddy/clash_rules/China.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ChinaIPs/ChinaIPs_Classical.yaml -O /usr/share/caddy/clash_rules/ChinaIPs_Classical.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/GlobalMedia/GlobalMedia.yaml -O /usr/share/caddy/clash_rules/GlobalMedia.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Global/Global_Classical.yaml -O /usr/share/caddy/clash_rules/Global_Classical.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Advertising/Advertising_Classical.yaml -O /usr/share/caddy/clash_rules/Advertising_Classical.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml -O /usr/share/caddy/clash_rules/Privacy_Classical.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Hijacking/Hijacking.yaml -O /usr/share/caddy/clash_rules/Hijacking.yaml
wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Microsoft/Microsoft.yaml -O /usr/share/caddy/clash_rules/Microsoft.yaml
wget https://raw.githubusercontent.com/dtking-4/self-use/main/rule.yaml -O /usr/share/caddy/clash_rules/SelfRules.yaml
